version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_DSN=postgres:postgres@postgres:5432/app_db?sslmode=disable
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=postgres
      # - DB_PASSWORD=postgres
      # - DB_NAME=app_db
      # - DB_SSL_MODE=disable
      - BASE_URL=http://localhost:8080
      - HTTP_PORT=8080
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: