apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: postgres
  postgres-db: app_db
  db-dsn: postgres:postgres@postgres:5432/app_db?sslmode=disable